apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bcuttino-poi-map-app-dev
  annotations:
    argocd/app-name: bcuttino-poi-map-app-dev
    backstage.io/kubernetes-id: bcuttino-poi-map-app
    backstage.io/kubernetes-namespace: bcuttino
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/bcuttino-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/bcuttino/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/bcuttino/deployments/bcuttino-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/bcuttino-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://bcuttino-poi-map-app-bcuttino.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/bcuttino"
  system: workshop-system-bcuttino
  consumesApis:
    - gateway-api-bcuttino
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-bcuttino
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/bcuttino"
